name: Deploy Sanity Studio

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: Restore cached Node Modules 💾
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Deploy Studio
        run: npm run deploy 